#############################################################################
# Makefile for building: SourceManager
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  SourceManager.pro
# Template: app
# Command: "S:\Qt 6\6.5.3\msvc2019_64\bin\qmake.exe" -o Makefile SourceManager.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = "S:\Qt 6\6.5.3\msvc2019_64\bin\qmake.exe"
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = "S:\Qt 6\6.5.3\msvc2019_64\bin\qmake.exe" -install qinstall
QINSTALL_PROGRAM = "S:\Qt 6\6.5.3\msvc2019_64\bin\qmake.exe" -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = SourceManager_resource.res
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: SourceManager.pro "S:\Qt 6\6.5.3\msvc2019_64\mkspecs\win32-msvc\qmake.conf" "S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\spec_pre.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\windows-desktop.conf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\windows-vulkan.conf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\msvc-desktop.conf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\qconfig.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_grpc.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_grpc_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_httpserver.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_httpserver_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttracker.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttracker_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_location.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_protobuf.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_protobuf_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webview.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qt_functions.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qt_config.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\win32-msvc\qmake.conf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\spec_post.prf" \
		.qmake.stash \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\msvc-version.conf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\toolchain.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\default_pre.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\default_pre.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\resolve_config.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds_post.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\default_post.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qtquickcompiler.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\entrypoint.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\precompile_header.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\warn_on.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qt.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\resources_functions.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\resources.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\moc.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\opengl.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\uic.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qmake_use.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\file_copies.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\windows.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\testcase_targets.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\exceptions.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\yacc.prf" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\lex.prf" \
		SourceManager.pro \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Widgets.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Gui.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Sql.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Core.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6EntryPoint.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\build_pass.prf" \
		res.qrc \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Widgetsd.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Guid.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Sqld.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Cored.prl" \
		"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6EntryPointd.prl"
	$(QMAKE) -o Makefile SourceManager.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\spec_pre.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\windows-desktop.conf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\windows-vulkan.conf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\msvc-desktop.conf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\qconfig.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_grpc.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_grpc_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_httpserver.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_httpserver_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttracker.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttracker_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_location.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_protobuf.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_protobuf_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webview.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qt_functions.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qt_config.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\win32-msvc\qmake.conf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\spec_post.prf":
.qmake.stash:
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\common\msvc-version.conf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\toolchain.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\default_pre.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\default_pre.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\resolve_config.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds_post.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\default_post.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qtquickcompiler.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\entrypoint.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\precompile_header.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\warn_on.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qt.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\resources_functions.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\resources.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\moc.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\opengl.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\uic.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\qmake_use.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\file_copies.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\win32\windows.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\testcase_targets.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\exceptions.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\yacc.prf":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\lex.prf":
SourceManager.pro:
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Widgets.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Gui.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Sql.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Core.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6EntryPoint.prl":
"S:\Qt 6\6.5.3\msvc2019_64\mkspecs\features\build_pass.prf":
res.qrc:
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Widgetsd.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Guid.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Sqld.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6Cored.prl":
"S:\Qt 6\6.5.3\msvc2019_64\lib\Qt6EntryPointd.prl":
qmake: FORCE
	@$(QMAKE) -o Makefile SourceManager.pro -spec win32-msvc "CONFIG+=qtquickcompiler"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
